import Link from "next/link";import {getAnalytics,getBrain,getProduct,getSubreddits} from "@/lib/api";import RebuildBrainButton from "./RebuildBrainButton";

function Items({items}:{items?:string[]}){return items?.length?<ul>{items.map((item,i)=><li key={i}>{item}</li>)}</ul>:<p>Not identified.</p>}

export default async function ProductPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const [p,brain,a,subs]=await Promise.all([getProduct(id),getBrain(id),getAnalytics(id),getSubreddits(id)]);if(!p)return <p>Product not found.</p>;const b=brain?.brain||{};return <><div className="eyebrow">Product control · Brain v{brain?.version||"—"}</div><h1>{p.name}</h1><p>{b.one_liner||"Product Brain has not been built yet."}</p><div className="actions"><Link className="button secondary" href={`/products/${id}/opportunities`}>Opportunities</Link><Link className="button secondary" href={`/products/${id}/conversations`}>Conversations</Link><Link className="button secondary" href={`/products/${id}/safety`}>Safety</Link><RebuildBrainButton productId={id}/></div><section className="grid"><div className="card"><div className="label">Status</div><div className="metric" style={{fontSize:20}}>{p.status}</div></div><div className="card"><div className="label">Autopublish</div><div className="metric" style={{fontSize:20}}>{p.autopublish_enabled?"Product on":"Product off"}</div></div><div className="card"><div className="label">Daily cap</div><div className="metric">{p.daily_reply_limit}</div></div><div className="card"><div className="label">Communities</div><div className="metric">{subs.length}</div></div>
<div className="card wide"><div className="label">Product Brain</div><h2>{b.category||"Unknown category"}</h2><p><strong>Disclosure:</strong> {p.disclosure_template||b.disclosure_identity}</p><p><strong>Pricing:</strong> {b.pricing_summary||"Not verified"}</p><p><strong>Target users:</strong> {(b.target_users||[]).join(", ")||"Not set"}</p></div>
<div className="card wide"><div className="label">Jobs to be done</div><Items items={b.jobs_to_be_done}/></div>
<div className="card wide"><div className="label">Pain points</div><Items items={b.pain_points}/></div>
<div className="card wide"><div className="label">Use cases</div><Items items={b.use_cases}/></div>
<div className="card wide"><div className="label">Recommend when</div><Items items={b.recommend_when}/></div>
<div className="card wide"><div className="label">Do not recommend when</div><Items items={b.do_not_recommend_when}/></div>
<div className="card wide"><div className="label">Evidence-backed claims</div>{(b.supported_claims||[]).map((c:any,i:number)=><div key={i}><p><span className="status">{Math.round((c.confidence||0)*100)}% evidence</span> {c.claim}</p><blockquote>{c.source_quote}</blockquote></div>)}{!(b.supported_claims||[]).length&&<p>No supported claims yet.</p>}</div>
<div className="card wide"><div className="label">Uncertain or unsupported</div><Items items={b.unsupported_or_uncertain_claims}/></div>
<div className="card wide"><div className="label">High-intent retrieval signals</div><p><strong>Direct:</strong> {(b.query_graph?.direct_terms||[]).join(" · ")||"Not set"}</p><p><strong>Pain language:</strong> {(b.query_graph?.pain_phrases||[]).join(" · ")||"Not set"}</p><p><strong>Intent:</strong> {(b.query_graph?.intent_patterns||[]).join(" · ")||"Not set"}</p></div>
<div className="card wide"><div className="label">Tracking SDK</div><pre>{`<script src="${process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000"}/v1/tracking/sdk.js" data-project="${p.id}"></script>`}</pre></div><div className="card wide"><div className="label">Current funnel</div><p>Scanned {a?.scanned??0}, qualified {a?.qualified_opportunities??0}, visits {a?.visits??0}, signups {a?.signups??0}, activations {a?.activations??0}.</p></div></section></>}
